spring.application.name=desafio-fullstack
spring.datasource.url=jdbc:postgresql://localhost:5432/teamguide_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


spring.sql.init.mode=always